# Generated by Django 3.0.9 on 2020-08-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Ui', 'UI'), ('Functional', 'Functional'), ('DB', 'DB'), ('Other', 'Others')], default='Functional', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('TBD', 'TBD')], default='Open', max_length=10)),
            ],
        ),
    ]
