# Generated by Django 3.0.9 on 2020-08-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemodel',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
