# Generated by Django 3.0.9 on 2020-08-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0002_issuemodel_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemodel',
            name='create_by',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='issuemodel',
            name='created_on',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='issuemodel',
            name='logged_by',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='issuemodel',
            name='desc',
            field=models.TextField(default=None),
        ),
    ]
