# Generated by Django 3.0.9 on 2020-08-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0004_auto_20200805_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='environment',
            field=models.CharField(choices=[('Production', 'Production')], default='Prod', max_length=20),
        ),
    ]
